local:
  big-image:
    path: ./resources/big-images
  small-image:
    path: ./resources/small-images

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: yugioh
    password: yugioh
    url: jdbc:p6spy:postgresql://localhost:5432/yugioh
    tomcat:
      max-active: 500
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: false


security:
  encoding-strength: 256
  jwt:
    client-id: yugiohjwtclientid
    client-secret: XY7kmzoNzl100
    grant-type: password
    resource-ids: yugiohjwtresourceid
    scope-read: read
    scope-write: write
  oauth2:
    resource:
      filter-order: 3
  security-realm: Yu-Gi-Oh JWT Realm
  signing-key: kzPC57LMaYzkSjm


argon2-parameters:
  salt-length: 128
  hash-length: 128
  parallelism: 2
  memory: 2096
  iterations: 3


server:
  location: http://localhost:8080 # TODO: Change this when deploying